### ISSUE TITLE
Add uofw types similar to pspsdk_types

### ISSUE THREAD

**Issue by sajattack** [pspdev/psp-ghidra-scripts#10]
UOFW has many more kernel-specific types than are available in pspsdk, so I think we should have both if possible. I tried myself and got really frustrated with Ghidra's C parser.

**Comment by John-K** [comment]
I can take a shot at it, which files are you trying to do this for?

**Comment by sajattack** [comment]
This would be a good one to start with https://github.com/uofw/uofw/blob/b0146f24a25b24454da7c488ceba4b0fadca0530/include/loadcore.h

But basically all the headers that have types.

**Comment by artart78** [comment]
I think the .gdt files (+ the short guide if you want to regenerate them) are good enough, @sajattack do you agree?

**Comment by sajattack** [comment]
Yep thanks
